### Get unique reference
GET http://localhost:3000/momoAuth/getReferenceId

### Create API user
POST http://localhost:3000/momoAuth/createApiUser

### Confirm API user
GET http://localhost:3000/momoAuth/confirmApiUser

### Get API key
POST http://localhost:3000/momoAuth/getApiKey

### Get access token
POST http://localhost:3000/momoAuth/getAccessToken